<!DOCTYPE html>
<html>
<head>
  <title>Slim 4 PHP Template</title>

  <link rel='stylesheet' type='text/css' href='assets/css/style.css'>
  <link rel='stylesheet' type='text/css' href='assets/css/header.css'>
  <link rel='stylesheet' type='text/css' href='assets/css/footer.css'>
<style type="text/css">
  <?php
    if(isset($pageTitle)) {
      switch($pageTitle) {
        case "index":
//          echo file_get_contents(__DIR__ . '/../public/assets/css/index.css');
          break;
        case "register":
          echo "<link rel='stylesheet' type='text/css' src='assets/css/register.css'>";
          break;
        case "dashboard":
          echo "<link rel='stylesheet' type='text/css' src='assets/css/dashboard.css'>";
          break;
      }
    }
  ?>
</style>
</head>
<body>
  <header>
    <div>
      <div class="page-title">
        <h1>Slim 4 PHP Template</h1>
      </div>
      <div class="page-navigation">
        <nav>
          <ul>
            <li>Home</li>
            <li>About</li>
            <li>Support</li>
          </ul>
        </nav>
      </div>
      <div class="header-addition">
        <div>
          <ul>
            <li>
              Twitter
            </li>
            <li>
              Facebook
            </li>
            <li>
            Youtube
          </li>
          <li>
            VK
          </li>
        </ul>
      </div>
      <div>
        <div id="currentTime">
         <span><?php echo date('H:i:s'); ?></span>
        </div>
        <div id="currentDate">
          <span><?php echo date('d/m/Y'); ?></span>
        </div>
      </div>
    </div>
  </header>
  <main>
    <div>
