<!DOCTYPE html>
<html>
<head>
  <title>Slim 4 PHP Template</title>
</head>
<body>
  <header>
    <div>
      <h1>Slim 4 PHP Template</h1>
    </div>
    <div>
      <nav>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Support</li>
        </ul>
      </nav>
    </div>
    <div>
      <div>
        <ul>
          <li>
            Twitter
          </li>
          <li>
            Facebook
          </li>
          <li>
            Youtube
          </li>
          <li>
            VK
          </li>
        </ul>
      </div>
      <div>
        <div id="timestamp">
          <?php echo date('H:i:s'); ?>
        </div>
        <div>
          <?php echo date('d/m/Y'); ?>
        </div>
      </div>
    </div>
  </header>
  <main>
    <div>
